global:
  resolve_timeout: 1m

route:
  receiver: slack_notifications

receivers:
  - name: slack_notifications
    slack_configs:
      - api_url: "-to be replaced with the actual webhook from slack as this was made for test and it triggers security alerd on github"
        channel: "#alerts"
